### ISSUE TITLE
Logs from Ansible Resource Model in Jobs logs

### ISSUE THREAD

**Issue by shoelzle** [rundeck-plugins/ansible-plugin#89] opened 2017-01-04 11:38 UTC
Hello,

My Rundeck uses an Ansible Resource Model for gathering nodes.
The logs from the exections of the Ansible Resource Model are shown in job logs.

Versions:
Ansible-Version: 2.2.0
Rundeck-Ansible-Plugin-Version: 2.0.2
Rundeck-Version: 2.7.0-1

If more information is needed, please let me know.

Best Regards
Stefan

**Comment by mnasiadka** [comment] 2017-01-09 13:51
Same issue here...
Versions:
Ansible-Version: 2.2.0
Rundeck-Ansible-Plugin-Version: 2.0.2
Rundeck-Version: 2.7.1-1

**Comment by Kurisutian** [comment] 2017-01-25 08:13
It also affects me...
Versions:
Ansible-Version: 2.2.0
Rundeck-Ansible-Plugin-Version: 2.0.2
Rundeck-Version: 2.7.0-1

**Comment by haselere** [comment] 2017-03-21 12:37
Same here:
Versions:
Ansible-Version: 2.2.0
Rundeck-Ansible-Plugin-Version: 2.0.2
Rundeck-Version: 2.7.0-1

**Comment by DerekTBrown** [comment] 2017-08-09 04:58
This is because it is a workflow step, and not an execution.  Closing.

**Closed as completed by DerekTBrown** 2017-08-09 04:58 UTC
Labels: enhancement

**Comment by shoelzle** [comment] 2017-08-10 18:47
@DerekTBrown , you provided an explanation for this issue, but no solution. Thus this is still an issue and an annoying one. Please reopen the issue.
Maybe the logs from the resource model can be logged to some other logfile ?

**Comment by DerekTBrown** [comment] 2017-08-10 20:30
@shoelzle This is the expected behavior of the application.  It is executing an Ansible playbook as a job, so it is passed into the Rundeck job log.  We welcome a pull request if this is a mission-critical feature for you, but it is not a priority for the project as a whole, we have bigger fish to fry.

**Comment by shoelzle** [comment] 2017-09-06 14:14
Hello @DerekTBrown , I understand that the behavior is as expected and I'm with you: it's not a critical feature and there are more important issues. Nonetheless I think the logs from the resource model have no place in executions logs and therefore I don't understand why you closed this issue.

**Comment by DerekTBrown** [comment] 2017-09-06 17:23
@shoelzle because its not something that we can fix in this repository. It would require manually overriding the logging behavior of Rundeck itself.
