### ISSUE TITLE
SSH Node executor didn't receive port from Ansible Resource Model

### ISSUE THREAD

**Issue by uritau** [rundeck-plugins/ansible-plugin#111] opened 2017-04-27 07:56 UTC
I have a hosts file like this:
```

[Development_servers]
srv1 ansible_host=server1.test.com ansible_ssh_user=root
srv2 ansible_host=server2.test.com ansible_ssh_port=2222 ansible_ssh_user=root
```
If I configure my project using **Ansible Resource Model Source** and **SSH as Default Node Executor**, the srv1 works but the srv2 fails. 
Monitoring network traffic I see that the srv2 connection is trying to reach port 22, not 2222. I think that SSH did not receive the port from the Resource Model.
If I configure the Ansible Ad-Hoc Node executor, the job works fine, but I need to use SSH executor.

I don't know if it's an Issue or it is intended to avoid this kind of configuration. 
But I think the Resource Model must be independent of Node Executor.

Thanks for your help!
If you need some logs or other debug stuff, ask for it please!

**Comment by DerekTBrown** [comment] 2017-08-09 20:06
This is known behavior (it will not pass configuration back to Rundeck resources).  This is a duplicate of a couple of other issues on the subject.

**Closed as completed by DerekTBrown** 2017-08-09 20:06 UTC
Labels: question
